### ISSUE TITLE
Getting error 'Missing required parameter: client_id'

### ISSUE THREAD

**Issue by ktlotleng** [rbouteiller/spotifydl#1]
After the script open the external link (browser) and I try to log into Spotify I get 'Missing required parameter: client_id' and thus cannot continue further.

**Comment by rbouteiller** [comment]
Yes in the spotify.py file on line 11 & 12 you have to insert your spotify API ids
`# Spotify API
client_id = 'INSERT CLIENT ID HERE'
client_secret = 'INSERT CLIENT SECRET HERE'`

**Comment by rbouteiller** [comment]
I've added a readme with some instructions

**Comment by ktlotleng** [comment]
More instruction are needed. I was able to resolve this issue but came across another issue which I will open as a separate issue. I believe you should let people know that they have to:

1. Create/have a Spotify developer account to geta client id and client secret.
2. Copy the client id and secrete into the python script.
3. The redirect url on the Spotify developer dashboard should be the same as the one on the script? Which is http://localhost:5000/?
4. Save and run the script?

**Comment by FusionIX** [comment]
i have this issue too i get onto the thing where it says accept and whatever you named the app shows up saying it can change/control and then  you accept and it just says localhost refused to connect so what do i do from here?

**Comment by rbouteiller** [comment]
From localhost refused to connect you should copy the url in the program
