### ISSUE TITLE
getting error  'INVALID_CLIENT: Invalid redirect URI'

### ISSUE THREAD

**Issue by FusionIX** [rbouteiller/spotifydl#2]
i do the command python spotify.py on command line and then it shows that error or whatever it is how do i fix it ?

**Comment by rbouteiller** [comment]
<img width="893" alt="Screenshot 2024-01-04 at 20 13 37" src="https://github.com/rbouteiller/spotifydl/assets/50409352/bb6eb5aa-9080-448a-93d6-e66a59460c71">

In the spotify developer portal you have to add a Redirect URL `http://localhost:5000/`

**Comment by FusionIX** [comment]
i did that and then it just says  this site cant be reached it refused to connect

**Comment by rbouteiller** [comment]
You have to copy the url (of the site saying "site can't be reached") in the python program
